repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/econchick/interrogate
    rev: 1.1.4  # or master if you're bold
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=80]