repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/econchick/interrogate
    rev: 1.1.4
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=80]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--verbose']
        additional_dependencies:
          - 'flake8-bugbear'
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
