version: 2.1

orbs:
  python: circleci/python@0.3.0
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps:
          dependency-file: requirements-dev.txt
      - python/save-cache
      - run:
          command: |
            interrogate -v -M -p -r 'Test*' app
          name: Run docstring analysis
      - run:
          command: |
            coverage run --source app -m pytest tests
            coverage report --skip-empty --fail-under=50
          name: Run tests
      - coveralls/upload

workflows:
  main:
    jobs:
      - build-and-test
